//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "charging_station")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub addresses: String,
    pub area: String,
    pub city: String,
    pub company: String,
    pub created_time: DateTime,
    pub ctype: String,
    pub dial: String,
    pub features: String,
    pub geometry: String,
    pub grestr: String,
    pub height: String,
    pub heightrestricted: String,
    pub images: String,
    pub info: String,
    pub is_deleted: String,
    pub lat: String,
    pub lng: String,
    pub num: String,
    pub openinghours: String,
    pub phone: String,
    pub postcode: String,
    pub pr: String,
    pub priceschema: String,
    pub ptype: String,
    pub rating: String,
    pub street: String,
    pub surface: String,
    pub timezoneid: String,
    pub title: String,
    pub r#type: String,
    pub typeid: String,
    pub updated_time: DateTime,
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
